version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/www
    ports:
      - 4567:4567
    environment:
      OTEL_EXPORTER_JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
      OTEL_TRACES_EXPORTER: 'jaeger'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
