# frozen_string_literal: true

source 'http://rubygems.org'

gem 'opentelemetry-exporter-jaeger'
gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-sdk'
gem 'pry'
gem 'pry-byebug'
gem 'rspec'
gem 'sinatra'
