version: '3'

services:
  app:
    build: .
    image: counting_valleys:latest
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    ports:
      - 4567:4567
    volumes:
      - ./:/www
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 14268:14268
      - 14250:14250
  otel-collector:
    image: otel/opentelemetry-collector
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4318:4318
