apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-and-a-mouse-deployment
  labels:
    app: cats-and-a-mouse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats-and-a-mouse
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "4567"
      labels:
        app: cats-and-a-mouse
    spec:
      containers:
        - name: cats-and-a-mouse
          image: flaviogf/cats_and_a_mouse:0.0.5
          ports:
            - containerPort: 4567
          livenessProbe:
            httpGet:
              path: /healthy
              port: 4567
            initialDelaySeconds: 1
            periodSeconds: 5
