apiVersion: batch/v1
kind: Job
metadata:
  name: eletronics-shop-job
  labels:
    app: eletronics-shop
spec:
  template:
    metadata:
      labels:
        app: eletronics-shop
    spec:
      containers:
        - name: eletronics-shop
          image: flaviogf/eletronics_shop:0.0.1
      restartPolicy: Never
