apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickingnumbers-deployment
  labels:
    app: pickingnumbers
spec:
  selector:
    matchLabels:
      app: pickingnumbers
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      labels:
        app: pickingnumbers
    spec:
      containers:
        - name: pickingnumbers
          image: flaviogf/pickingnumbers:0.0.3
          ports:
            - containerPort: 8080
